version: '3'

services:

  api:
    build: .
    ports:
      - '4321:4321'
    depends_on:
      - postgres
    env_file:
      - .env
    container_name: orkg_simcomp_api_container
    restart: on-failure
    networks:
      - orkg_simcomp_api

  postgres:
    image: "postgres:11-alpine"
    container_name: orkg_simcomp_postgres_container
    environment:
      - POSTGRES_USER=${ORKG_SIMCOMP_API_POSTGRES_USER}
      - POSTGRES_PASSWORD=${ORKG_SIMCOMP_API_POSTGRES_PASSWORD}
      - POSTGRES_DB=${ORKG_SIMCOMP_API_POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - 'postgres:/usr/share/postgresql/data'
    networks:
      - orkg_simcomp_api

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    container_name: orkg_simcomp_es01_container
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - orkg_simcomp_api

networks:
  orkg_simcomp_api:

volumes:
  postgres:
    driver: local
  esdata01:
    driver: local