#!/bin/bash

if [[ "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" == "main" ]]; then

  if [[ "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME" == "dev" ]]; then
    echo "Merging from dev to main is allowed!"
    exit 0

  else
    echo "Merging to 'main' is only allowed from 'dev' !!"
    exit 1
  fi

else
  echo "Merging is allowed!"
  exit 0

fi